In [1]:
import numpy as np
import pandas as pd

In [2]:
X = np.array([[1 ,2 ],[2, 3]])

In [3]:
X

array([[1, 2],
       [2, 3]])

In [12]:
xx=np.matmul(X.transpose(),X)

In [13]:
theta=np.array([1,2])
theta

array([1, 2])

In [14]:
np.dot(xx,theta)

array([21, 34])

In [15]:
2*theta

array([2, 4])

In [29]:
def compute_square_loss_gradient(X, y, theta):
    """
    Compute gradient of the square loss (as defined in compute_square_loss), at the point theta.

    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        theta - the parameter vector, 1D numpy array of size (num_features)

    Returns:
        grad - gradient vector, 1D numpy array of size (num_features)
    """
    #TODO
    m=y.shape[0]
    xx = np.matmul(X.transpose(),X)
    return 2/m*(np.dot(xx,theta)-np.dot(X.transpose(),y))

In [30]:
X = np.array([[1 ,2 ],[2, 3]])

In [31]:
theta=np.array([1,2])

In [32]:
y=np.array([1,3])

In [33]:
compute_square_loss_gradient(X, y, theta)

array([14., 23.])

In [36]:
def compute_square_loss(X, y, theta):
    """
    Given a set of X, y, theta, compute the square loss for predicting y with X*theta

    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        theta - the parameter vector, 1D array of size (num_features)

    Returns:
        loss - the square loss, scalar
    """
    #loss = 0 #initialize the square_loss
    #TODO
    
    return np.linalg.norm(np.dot(X,theta)-y,ord=2)**2/y.shape[0]

In [37]:
compute_square_loss(X, y, theta)

20.5

In [40]:
for x in range(1, 3):
    print ("We're on time %d" % (x))

We're on time 1
We're on time 2


In [42]:
np.linalg.norm(np.array([1,2]),ord=2)

2.23606797749979

In [43]:
10e-3

0.01

In [4]:
import pandas as pd
import logging
import numpy as np
import sys
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

In [5]:
def feature_normalization(train, test):
    """Rescale the data so that each feature in the training set is in
    the interval [0,1], and apply the same transformations to the test
    set, using the statistics computed on the training set.

    Args:
        train - training set, a 2D numpy array of size (num_instances, num_features)
        test  - test set, a 2D numpy array of size (num_instances, num_features)
    Returns:
        train_normalized - training set after normalization
        test_normalized  - test set after normalization

    """
    # TODO
    """
    1. concate train and test along the axis 0
       new=np.concatenate((train,test),axis=0)

    2. drop the constant feature
       2.1 Compare each value to the corresponding value in the first row:

        In [46]: a == a[0,:]
        Out[46]: 
        array([[ True,  True,  True],
               [ True, False,  True],
               [ True, False,  True],
               [ True,  True,  True]], dtype=bool)
               
        2.2 A column shares a common value if all the values in that column are True:

        In [47]: indices=np.all(a == a[0,:], axis = 0)
        # or indices=(a==a[0,:]).all(axis=0)
        In [48]: indices
        Out[49]: array([ True, False,  True], dtype=bool)

        2.3 get arr using boolean indices
        In [50]: a=a[:,~indices]

        online code:
        a=a[:,~np.all(a == a[0,:],axis=0)]
        or
        a=a[:,~(a==a[0,:]).all(axis=0)]

     
       indices=(new == new[0,:]).all(axis = 0)
       new= new[:,~indices]

    3. find max and min and rescale the feature
        
       maximum=new.max(axis=0) 
       minimum=new.min(axis=0)

       interval=maximum-minimum

       new=(new-min)/interval
    4. split back along axis 0
       [train_normalized, test_normalized]= np.split(new,[train.shape[0]])


    """
    #1. concate train and test along the axis 0
    new=np.concatenate((train,test),axis=0)

    #2. drop the constant feature
    indices=(new == new[0,:]).all(axis = 0)
    new= new[:,~indices]

    #3. find max and min and rescale the feature
    maximum=new.max(axis=0) 
    minimum=new.min(axis=0)
    interval=maximum-minimum
    new=(new-minimum)/interval

    #4. split back along axis 0
    [train_normalized, test_normalized]= np.split(new,[train.shape[0]])

    return train_normalized, test_normalized



In [6]:
def compute_square_loss(X, y, theta):
    """
    Given a set of X, y, theta, compute the square loss for predicting y with X*theta

    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        theta - the parameter vector, 1D array of size (num_features)

    Returns:
        loss - the square loss, scalar
    """
    #loss = 0 #initialize the square_loss
    #TODO
    
    return np.linalg.norm(np.dot(X,theta)-y,ord=2)**2/y.shape[0]

In [7]:
def compute_square_loss_gradient(X, y, theta):
    """
    Compute gradient of the square loss (as defined in compute_square_loss), at the point theta.

    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        theta - the parameter vector, 1D numpy array of size (num_features)

    Returns:
        grad - gradient vector, 1D numpy array of size (num_features)
    """
    #TODO
    m=y.shape[0]
    xx = np.matmul(X.transpose(),X)
    return -2/m*(np.dot(xx,theta)-np.dot(X.transpose(),y))


In [8]:
def batch_grad_descent(X, y, alpha=0.1, num_iter=1000, check_gradient=False):
    """
    In this question you will implement batch gradient descent to
    minimize the square loss objective

    Args:
        X - the feature vector, 2D numpy array of size (num_instances, num_features)
        y - the label vector, 1D numpy array of size (num_instances)
        alpha - step size in gradient descent
        num_iter - number of iterations to run
        check_gradient - a boolean value indicating whether checking the gradient when updating
        
        stop criterion 10e-6??

    Returns:
        theta_hist - store the the history of parameter vector in iteration, 2D numpy array of size (num_iter+1, num_features)
                    for instance, theta in iteration 0 should be theta_hist[0], theta in ieration (num_iter) is theta_hist[-1]
        loss_hist - the history of objective function vector, 1D numpy array of size (num_iter+1)
    """
    num_instances, num_features = X.shape[0], X.shape[1]
    theta_hist = np.zeros((num_iter+1, num_features))  #Initialize theta_hist
    loss_hist = np.zeros(num_iter+1) #initialize loss_hist
    theta = np.zeros(num_features) #initialize theta
    #TODO
    #solid alpha
    """
    for num in range(1,num_iter):
        loss_gradient = compute_square_loss_gradient(X, y, theta_hist[num-1])
        if np.linalg.norm(loss_gradient,ord=2) <= 10e-6:
            break
        theta_hist[num] =theta_hist[num-1] + alpha*loss_gradient
        loss_hist[num] = compute_square_loss(X, y, theta_hist[num])

    return theta_hist, loss_hist
    """
####################################
###Q2.4b: Implement backtracking line search in batch_gradient_descent
###Check http://en.wikipedia.org/wiki/Backtracking_line_search for details
#TODO
   # backtracking line search
    for num in range(1,num_iter):
        loss_gradient = compute_square_loss_gradient(X, y, theta_hist[num-1,:])
        if np.linalg.norm(loss_gradient,ord=2) <= 10e-6:
            break
        c=0.5
        gamma=0.5
        delta = c*loss_gradient 
        loss_hist[num] = compute_square_loss(X, y, theta_hist[num-1,:] + loss_gradient.transpose())
        t=1
        while loss_hist[num] > loss_hist[num-1]+t*delta:
            t=gamma*t
            theta_hist[num]=theta_hist[num-1,:] + t*loss_gradient
            loss_hist[num]= compute_square_loss(X, y, theta_hist[num,:])
    return theta_hist, loss_hist
        


In [9]:
def main():
    #Loading the dataset
    print('loading the dataset')

    df = pd.read_csv('data.csv', delimiter=',')
    X = df.values[:,:-1]
    y = df.values[:,-1]

    print('Split into Train and Test')
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size =100, random_state=10)

    print("Scaling all to [0, 1]")
    X_train, X_test = feature_normalization(X_train, X_test)
    X_train = np.hstack((X_train, np.ones((X_train.shape[0], 1))))  # Add bias term
    X_test = np.hstack((X_test, np.ones((X_test.shape[0], 1)))) # Add bias term

    # TODO

    theta_history, loss_history=batch_grad_descent(X_train, y_train, alpha=0.1, num_iter=1000, check_gradient=True)

if __name__ == "__main__":
    main()

loading the dataset
Split into Train and Test
Scaling all to [0, 1]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [10]:
x=np.array([[1,2],[3,4]])
x

array([[1, 2],
       [3, 4]])

In [11]:
y=np.array([1,2])

In [12]:
y

array([1, 2])

In [13]:
x[1,:]+y

array([4, 6])

In [14]:
x[0,:]+y

array([2, 4])